"""Create tables

Revision ID: 39f5b29a59f0
Revises: 6e871d4c2043
Create Date: 2023-07-19 13:32:15.381943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f5b29a59f0'
down_revision = '6e871d4c2043'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('Title', sa.String(), nullable=True),
    sa.Column('Desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    schema='tenant1'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table', schema='tenant1')
    # ### end Alembic commands ###
