"""Create tables

Revision ID: 4ef7c66149c8
Revises: 2c6e7d073965
Create Date: 2023-07-19 13:24:32.749584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef7c66149c8'
down_revision = '2c6e7d073965'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('Title', sa.String(), nullable=True),
    sa.Column('Desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    schema='tenant2'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table', schema='tenant2')
    # ### end Alembic commands ###
