"""Create tables

Revision ID: 6e871d4c2043
Revises: 4ef7c66149c8
Create Date: 2023-07-19 13:31:55.883542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e871d4c2043'
down_revision = '4ef7c66149c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
