"""Create tables

Revision ID: f49ca173dcc2
Revises: 39f5b29a59f0
Create Date: 2023-07-19 13:32:31.624128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49ca173dcc2'
down_revision = '39f5b29a59f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('Title', sa.String(), nullable=True),
    sa.Column('Desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    schema='tenant3'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table', schema='tenant3')
    # ### end Alembic commands ###
